development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: postgres
  password: admin